//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using PropHunt.Mixed.Components;

namespace PropHunt.Generated
{
    [BurstCompile]
    public struct PropHuntMixedComponentsFloorMovementGhostComponentSerializer
    {
        static PropHuntMixedComponentsFloorMovementGhostComponentSerializer()
        {
            State = new GhostComponentSerializer.State
            {
                GhostFieldsHash = 6104341673800988698,
                ExcludeFromComponentCollectionHash = 0,
                ComponentType = ComponentType.ReadWrite<PropHunt.Mixed.Components.FloorMovement>(),
                ComponentSize = UnsafeUtility.SizeOf<PropHunt.Mixed.Components.FloorMovement>(),
                SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                ChangeMaskBits = ChangeMaskBits,
                SendMask = GhostComponentSerializer.SendMask.Predicted,
                SendForChildEntities = 1,
                CopyToSnapshot =
                    new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                CopyFromSnapshot =
                    new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                RestoreFromBackup =
                    new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                CalculateChangeMask =
                    new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                        CalculateChangeMask),
                Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                #endif
            };
            #if UNITY_EDITOR || DEVELOPMENT_BUILD
            State.NumPredictionErrorNames = GetPredictionErrorNames(ref State.PredictionErrorNames);
            #endif
        }
        public static readonly GhostComponentSerializer.State State;
        public struct Snapshot
        {
            public int floorVelocity_x;
            public int floorVelocity_y;
            public int floorVelocity_z;
            public int frameDisplacement_x;
            public int frameDisplacement_y;
            public int frameDisplacement_z;
        }
        public const int ChangeMaskBits = 2;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.FloorMovement>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.floorVelocity_x = (int) math.round(component.floorVelocity.x * 100);
                snapshot.floorVelocity_y = (int) math.round(component.floorVelocity.y * 100);
                snapshot.floorVelocity_z = (int) math.round(component.floorVelocity.z * 100);
                snapshot.frameDisplacement_x = (int) math.round(component.frameDisplacement.x * 100);
                snapshot.frameDisplacement_y = (int) math.round(component.frameDisplacement.y * 100);
                snapshot.frameDisplacement_z = (int) math.round(component.frameDisplacement.z * 100);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                float snapshotInterpolationFactor = snapshotInterpolationData.InterpolationFactor;
                ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.FloorMovement>(componentData, componentStride*i);
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                component.floorVelocity = math.lerp(
                    new float3(snapshotBefore.floorVelocity_x * 0.01f, snapshotBefore.floorVelocity_y * 0.01f, snapshotBefore.floorVelocity_z * 0.01f),
                    new float3(snapshotAfter.floorVelocity_x * 0.01f, snapshotAfter.floorVelocity_y * 0.01f, snapshotAfter.floorVelocity_z * 0.01f),
                    snapshotInterpolationFactor);
                component.frameDisplacement = math.lerp(
                    new float3(snapshotBefore.frameDisplacement_x * 0.01f, snapshotBefore.frameDisplacement_y * 0.01f, snapshotBefore.frameDisplacement_z * 0.01f),
                    new float3(snapshotAfter.frameDisplacement_x * 0.01f, snapshotAfter.frameDisplacement_y * 0.01f, snapshotAfter.frameDisplacement_z * 0.01f),
                    snapshotInterpolationFactor);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.FloorMovement>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.FloorMovement>(backupData, 0);
            component.floorVelocity.x = backup.floorVelocity.x;
            component.floorVelocity.y = backup.floorVelocity.y;
            component.floorVelocity.z = backup.floorVelocity.z;
            component.frameDisplacement.x = backup.frameDisplacement.x;
            component.frameDisplacement.y = backup.frameDisplacement.y;
            component.frameDisplacement.z = backup.frameDisplacement.z;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            snapshot.floorVelocity_x = predictor.PredictInt(snapshot.floorVelocity_x, baseline1.floorVelocity_x, baseline2.floorVelocity_x);
            snapshot.floorVelocity_y = predictor.PredictInt(snapshot.floorVelocity_y, baseline1.floorVelocity_y, baseline2.floorVelocity_y);
            snapshot.floorVelocity_z = predictor.PredictInt(snapshot.floorVelocity_z, baseline1.floorVelocity_z, baseline2.floorVelocity_z);
            snapshot.frameDisplacement_x = predictor.PredictInt(snapshot.frameDisplacement_x, baseline1.frameDisplacement_x, baseline2.frameDisplacement_x);
            snapshot.frameDisplacement_y = predictor.PredictInt(snapshot.frameDisplacement_y, baseline1.frameDisplacement_y, baseline2.frameDisplacement_y);
            snapshot.frameDisplacement_z = predictor.PredictInt(snapshot.frameDisplacement_z, baseline1.frameDisplacement_z, baseline2.frameDisplacement_z);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        private static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.floorVelocity_x != baseline.floorVelocity_x) ? 1u : 0;
            changeMask |= (snapshot.floorVelocity_y != baseline.floorVelocity_y) ? (1u<<0) : 0;
            changeMask |= (snapshot.floorVelocity_z != baseline.floorVelocity_z) ? (1u<<0) : 0;
            changeMask |= (snapshot.frameDisplacement_x != baseline.frameDisplacement_x) ? (1u<<1) : 0;
            changeMask |= (snapshot.frameDisplacement_y != baseline.frameDisplacement_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.frameDisplacement_z != baseline.frameDisplacement_z) ? (1u<<1) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 2);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.floorVelocity_x, baseline.floorVelocity_x, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.floorVelocity_y, baseline.floorVelocity_y, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.floorVelocity_z, baseline.floorVelocity_z, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.frameDisplacement_x, baseline.frameDisplacement_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.frameDisplacement_y, baseline.frameDisplacement_y, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.frameDisplacement_z, baseline.frameDisplacement_z, compressionModel);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.floorVelocity_x = reader.ReadPackedIntDelta(baseline.floorVelocity_x, compressionModel);
            else
                snapshot.floorVelocity_x = baseline.floorVelocity_x;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.floorVelocity_y = reader.ReadPackedIntDelta(baseline.floorVelocity_y, compressionModel);
            else
                snapshot.floorVelocity_y = baseline.floorVelocity_y;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.floorVelocity_z = reader.ReadPackedIntDelta(baseline.floorVelocity_z, compressionModel);
            else
                snapshot.floorVelocity_z = baseline.floorVelocity_z;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.frameDisplacement_x = reader.ReadPackedIntDelta(baseline.frameDisplacement_x, compressionModel);
            else
                snapshot.frameDisplacement_x = baseline.frameDisplacement_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.frameDisplacement_y = reader.ReadPackedIntDelta(baseline.frameDisplacement_y, compressionModel);
            else
                snapshot.frameDisplacement_y = baseline.frameDisplacement_y;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.frameDisplacement_z = reader.ReadPackedIntDelta(baseline.frameDisplacement_z, compressionModel);
            else
                snapshot.frameDisplacement_z = baseline.frameDisplacement_z;
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.FloorMovement>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.FloorMovement>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.floorVelocity, backup.floorVelocity));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.frameDisplacement, backup.frameDisplacement));
            ++errorIndex;
        }
        private static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("floorVelocity"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("frameDisplacement"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}