//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using PropHunt.Mixed.Components;

namespace PropHunt.Generated
{
    [BurstCompile]
    public struct PropHuntMixedComponentsMovementTrackingGhostComponentSerializer
    {
        static PropHuntMixedComponentsMovementTrackingGhostComponentSerializer()
        {
            State = new GhostComponentSerializer.State
            {
                GhostFieldsHash = 12720449746730225717,
                ExcludeFromComponentCollectionHash = 0,
                ComponentType = ComponentType.ReadWrite<PropHunt.Mixed.Components.MovementTracking>(),
                ComponentSize = UnsafeUtility.SizeOf<PropHunt.Mixed.Components.MovementTracking>(),
                SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                ChangeMaskBits = ChangeMaskBits,
                SendMask = GhostComponentSerializer.SendMask.Interpolated | GhostComponentSerializer.SendMask.Predicted,
                SendForChildEntities = 1,
                CopyToSnapshot =
                    new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                CopyFromSnapshot =
                    new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                RestoreFromBackup =
                    new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                CalculateChangeMask =
                    new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                        CalculateChangeMask),
                Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                #endif
            };
            #if UNITY_EDITOR || DEVELOPMENT_BUILD
            State.NumPredictionErrorNames = GetPredictionErrorNames(ref State.PredictionErrorNames);
            #endif
        }
        public static readonly GhostComponentSerializer.State State;
        public struct Snapshot
        {
            public int position_x;
            public int position_y;
            public int position_z;
            public int previousPosition_x;
            public int previousPosition_y;
            public int previousPosition_z;
            public int attitudeX;
            public int attitudeY;
            public int attitudeZ;
            public int attitudeW;
            public int previousAttitudeX;
            public int previousAttitudeY;
            public int previousAttitudeZ;
            public int previousAttitudeW;
            public int updates;
        }
        public const int ChangeMaskBits = 5;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.MovementTracking>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.position_x = (int) math.round(component.position.x * 100);
                snapshot.position_y = (int) math.round(component.position.y * 100);
                snapshot.position_z = (int) math.round(component.position.z * 100);
                snapshot.previousPosition_x = (int) math.round(component.previousPosition.x * 100);
                snapshot.previousPosition_y = (int) math.round(component.previousPosition.y * 100);
                snapshot.previousPosition_z = (int) math.round(component.previousPosition.z * 100);
                snapshot.attitudeX = (int)math.round(component.attitude.value.x * 100);
                snapshot.attitudeY = (int)math.round(component.attitude.value.y * 100);
                snapshot.attitudeZ = (int)math.round(component.attitude.value.z * 100);
                snapshot.attitudeW = (int)math.round(component.attitude.value.w * 100);
                snapshot.previousAttitudeX = (int)math.round(component.previousAttitude.value.x * 100);
                snapshot.previousAttitudeY = (int)math.round(component.previousAttitude.value.y * 100);
                snapshot.previousAttitudeZ = (int)math.round(component.previousAttitude.value.z * 100);
                snapshot.previousAttitudeW = (int)math.round(component.previousAttitude.value.w * 100);
                snapshot.updates = (int) component.updates;
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                float snapshotInterpolationFactor = snapshotInterpolationData.InterpolationFactor;
                ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.MovementTracking>(componentData, componentStride*i);
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                component.position = math.lerp(
                    new float3(snapshotBefore.position_x * 0.01f, snapshotBefore.position_y * 0.01f, snapshotBefore.position_z * 0.01f),
                    new float3(snapshotAfter.position_x * 0.01f, snapshotAfter.position_y * 0.01f, snapshotAfter.position_z * 0.01f),
                    snapshotInterpolationFactor);
                component.previousPosition = math.lerp(
                    new float3(snapshotBefore.previousPosition_x * 0.01f, snapshotBefore.previousPosition_y * 0.01f, snapshotBefore.previousPosition_z * 0.01f),
                    new float3(snapshotAfter.previousPosition_x * 0.01f, snapshotAfter.previousPosition_y * 0.01f, snapshotAfter.previousPosition_z * 0.01f),
                    snapshotInterpolationFactor);
                component.attitude = math.slerp(
                    math.normalize(new quaternion(snapshotBefore.attitudeX * 0.01f, snapshotBefore.attitudeY * 0.01f, snapshotBefore.attitudeZ * 0.01f, snapshotBefore.attitudeW * 0.01f)),
                    math.normalize(new quaternion(snapshotAfter.attitudeX * 0.01f, snapshotAfter.attitudeY * 0.01f, snapshotAfter.attitudeZ * 0.01f, snapshotAfter.attitudeW * 0.01f)),
                    snapshotInterpolationFactor);
                component.previousAttitude = math.slerp(
                    math.normalize(new quaternion(snapshotBefore.previousAttitudeX * 0.01f, snapshotBefore.previousAttitudeY * 0.01f, snapshotBefore.previousAttitudeZ * 0.01f, snapshotBefore.previousAttitudeW * 0.01f)),
                    math.normalize(new quaternion(snapshotAfter.previousAttitudeX * 0.01f, snapshotAfter.previousAttitudeY * 0.01f, snapshotAfter.previousAttitudeZ * 0.01f, snapshotAfter.previousAttitudeW * 0.01f)),
                    snapshotInterpolationFactor);
                component.updates = (int) snapshotBefore.updates;
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.MovementTracking>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.MovementTracking>(backupData, 0);
            component.position.x = backup.position.x;
            component.position.y = backup.position.y;
            component.position.z = backup.position.z;
            component.previousPosition.x = backup.previousPosition.x;
            component.previousPosition.y = backup.previousPosition.y;
            component.previousPosition.z = backup.previousPosition.z;
            component.attitude = backup.attitude;
            component.previousAttitude = backup.previousAttitude;
            component.updates = backup.updates;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            snapshot.position_x = predictor.PredictInt(snapshot.position_x, baseline1.position_x, baseline2.position_x);
            snapshot.position_y = predictor.PredictInt(snapshot.position_y, baseline1.position_y, baseline2.position_y);
            snapshot.position_z = predictor.PredictInt(snapshot.position_z, baseline1.position_z, baseline2.position_z);
            snapshot.previousPosition_x = predictor.PredictInt(snapshot.previousPosition_x, baseline1.previousPosition_x, baseline2.previousPosition_x);
            snapshot.previousPosition_y = predictor.PredictInt(snapshot.previousPosition_y, baseline1.previousPosition_y, baseline2.previousPosition_y);
            snapshot.previousPosition_z = predictor.PredictInt(snapshot.previousPosition_z, baseline1.previousPosition_z, baseline2.previousPosition_z);
            snapshot.attitudeX = predictor.PredictInt(snapshot.attitudeX, baseline1.attitudeX, baseline2.attitudeX);
            snapshot.attitudeY = predictor.PredictInt(snapshot.attitudeY, baseline1.attitudeY, baseline2.attitudeY);
            snapshot.attitudeZ = predictor.PredictInt(snapshot.attitudeZ, baseline1.attitudeZ, baseline2.attitudeZ);
            snapshot.attitudeW = predictor.PredictInt(snapshot.attitudeW, baseline1.attitudeW, baseline2.attitudeW);
            snapshot.previousAttitudeX = predictor.PredictInt(snapshot.previousAttitudeX, baseline1.previousAttitudeX, baseline2.previousAttitudeX);
            snapshot.previousAttitudeY = predictor.PredictInt(snapshot.previousAttitudeY, baseline1.previousAttitudeY, baseline2.previousAttitudeY);
            snapshot.previousAttitudeZ = predictor.PredictInt(snapshot.previousAttitudeZ, baseline1.previousAttitudeZ, baseline2.previousAttitudeZ);
            snapshot.previousAttitudeW = predictor.PredictInt(snapshot.previousAttitudeW, baseline1.previousAttitudeW, baseline2.previousAttitudeW);
            snapshot.updates = predictor.PredictInt(snapshot.updates, baseline1.updates, baseline2.updates);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        private static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.position_x != baseline.position_x) ? 1u : 0;
            changeMask |= (snapshot.position_y != baseline.position_y) ? (1u<<0) : 0;
            changeMask |= (snapshot.position_z != baseline.position_z) ? (1u<<0) : 0;
            changeMask |= (snapshot.previousPosition_x != baseline.previousPosition_x) ? (1u<<1) : 0;
            changeMask |= (snapshot.previousPosition_y != baseline.previousPosition_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.previousPosition_z != baseline.previousPosition_z) ? (1u<<1) : 0;
            changeMask |= (snapshot.attitudeX != baseline.attitudeX ||
                        snapshot.attitudeY != baseline.attitudeY ||
                        snapshot.attitudeZ != baseline.attitudeZ ||
                        snapshot.attitudeW != baseline.attitudeW) ? (1u<<2) : 0;
            changeMask |= (snapshot.previousAttitudeX != baseline.previousAttitudeX ||
                        snapshot.previousAttitudeY != baseline.previousAttitudeY ||
                        snapshot.previousAttitudeZ != baseline.previousAttitudeZ ||
                        snapshot.previousAttitudeW != baseline.previousAttitudeW) ? (1u<<3) : 0;
            changeMask |= (snapshot.updates != baseline.updates) ? (1u<<4) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 5);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.position_x, baseline.position_x, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.position_y, baseline.position_y, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.position_z, baseline.position_z, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.previousPosition_x, baseline.previousPosition_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.previousPosition_y, baseline.previousPosition_y, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.previousPosition_z, baseline.previousPosition_z, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
            {
                writer.WritePackedIntDelta(snapshot.attitudeX, baseline.attitudeX, compressionModel);
                writer.WritePackedIntDelta(snapshot.attitudeY, baseline.attitudeY, compressionModel);
                writer.WritePackedIntDelta(snapshot.attitudeZ, baseline.attitudeZ, compressionModel);
                writer.WritePackedIntDelta(snapshot.attitudeW, baseline.attitudeW, compressionModel);
            }
            if ((changeMask & (1 << 3)) != 0)
            {
                writer.WritePackedIntDelta(snapshot.previousAttitudeX, baseline.previousAttitudeX, compressionModel);
                writer.WritePackedIntDelta(snapshot.previousAttitudeY, baseline.previousAttitudeY, compressionModel);
                writer.WritePackedIntDelta(snapshot.previousAttitudeZ, baseline.previousAttitudeZ, compressionModel);
                writer.WritePackedIntDelta(snapshot.previousAttitudeW, baseline.previousAttitudeW, compressionModel);
            }
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedIntDelta(snapshot.updates, baseline.updates, compressionModel);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.position_x = reader.ReadPackedIntDelta(baseline.position_x, compressionModel);
            else
                snapshot.position_x = baseline.position_x;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.position_y = reader.ReadPackedIntDelta(baseline.position_y, compressionModel);
            else
                snapshot.position_y = baseline.position_y;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.position_z = reader.ReadPackedIntDelta(baseline.position_z, compressionModel);
            else
                snapshot.position_z = baseline.position_z;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.previousPosition_x = reader.ReadPackedIntDelta(baseline.previousPosition_x, compressionModel);
            else
                snapshot.previousPosition_x = baseline.previousPosition_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.previousPosition_y = reader.ReadPackedIntDelta(baseline.previousPosition_y, compressionModel);
            else
                snapshot.previousPosition_y = baseline.previousPosition_y;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.previousPosition_z = reader.ReadPackedIntDelta(baseline.previousPosition_z, compressionModel);
            else
                snapshot.previousPosition_z = baseline.previousPosition_z;
            if ((changeMask & (1 << 2)) != 0)
            {
                snapshot.attitudeX = reader.ReadPackedIntDelta(baseline.attitudeX, compressionModel);
                snapshot.attitudeY = reader.ReadPackedIntDelta(baseline.attitudeY, compressionModel);
                snapshot.attitudeZ = reader.ReadPackedIntDelta(baseline.attitudeZ, compressionModel);
                snapshot.attitudeW = reader.ReadPackedIntDelta(baseline.attitudeW, compressionModel);
            }
            else
            {
                snapshot.attitudeX = baseline.attitudeX;
                snapshot.attitudeY = baseline.attitudeY;
                snapshot.attitudeZ = baseline.attitudeZ;
                snapshot.attitudeW = baseline.attitudeW;
            }
            if ((changeMask & (1 << 3)) != 0)
            {
                snapshot.previousAttitudeX = reader.ReadPackedIntDelta(baseline.previousAttitudeX, compressionModel);
                snapshot.previousAttitudeY = reader.ReadPackedIntDelta(baseline.previousAttitudeY, compressionModel);
                snapshot.previousAttitudeZ = reader.ReadPackedIntDelta(baseline.previousAttitudeZ, compressionModel);
                snapshot.previousAttitudeW = reader.ReadPackedIntDelta(baseline.previousAttitudeW, compressionModel);
            }
            else
            {
                snapshot.previousAttitudeX = baseline.previousAttitudeX;
                snapshot.previousAttitudeY = baseline.previousAttitudeY;
                snapshot.previousAttitudeZ = baseline.previousAttitudeZ;
                snapshot.previousAttitudeW = baseline.previousAttitudeW;
            }
            if ((changeMask & (1 << 4)) != 0)
                snapshot.updates = reader.ReadPackedIntDelta(baseline.updates, compressionModel);
            else
                snapshot.updates = baseline.updates;
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.MovementTracking>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<PropHunt.Mixed.Components.MovementTracking>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.position, backup.position));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.previousPosition, backup.previousPosition));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.attitude.value, backup.attitude.value));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.previousAttitude.value, backup.previousAttitude.value));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.updates - backup.updates));
            ++errorIndex;
        }
        private static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("position"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("previousPosition"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("attitude"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("previousAttitude"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("updates"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}