name: Build Prod

on:
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForSomePlatforms:
    name: Build ${{ matrix.buildType }} for ${{ matrix.platform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ""
        unityVersion:
          - 2019.4.0f1
        platform:
          - OSX       # Build a macOS standalone (Intel 64-bit).
          - Windows   # Build a Windows standalone.
          - Windows64 # Build a Windows 64-bit standalone.
          - Linux64   # Build a Linux 64-bit standalone.
        buildType:
          - Client
          - Server
    steps:
      - uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Cache Library Folder
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.platform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Cache git lfs
        uses: actions/cache@v2
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1.2
          # use previous cache if current one is not found
          restore-keys: |
            ${{ runner.os }}-lfs-

      - name: Pull lfs data, if not cached
        run: git lfs pull

      - uses: webbertakken/unity-builder@v1.2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          buildMethod: EditorNamespace.ProdBuilder.${{ matrix.buildType }}_${{ matrix.platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.buildType }}
          path: Builds/*
