name: Build Prod

on:
  push: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildClientForSomePlatforms:
    name: Build Client for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ""
        unityVersion:
          - 2019.4.0f1
        targetPlatform:
          - StandaloneOSX       # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows   # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64   # Build a Linux 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v1.2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: build-${{ matrix.targetPlatform }}-Client
      - uses: actions/upload-artifact@v1
        with:
          name: Build-${{ matrix.targetPlatform }}-Client
          path: build-${{ matrix.targetPlatform }}-Client
  buildServerForSomePlatforms:
    name: Build Server for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ""
        unityVersion:
          - 2019.4.0f1
        targetPlatform:
          - StandaloneOSX       # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows   # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64   # Build a Linux 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v1.2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: build-${{ matrix.targetPlatform }}-Server
          customParameters: -ServerBuild
      - uses: actions/upload-artifact@v1
        with:
          name: Build-${{ matrix.targetPlatform }}-Server
          path: build-${{ matrix.targetPlatform }}-Server
