name Main

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    jobs:
        build:
          name: Build PropHunt ✨
          runs-on: ubuntu-latest
          steps:
            # Checkout
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                lfs: true

            # Cache
            - uses: actions/cache@v1.1.0
              with:
                path: Library
                key: Library

            # Test
            - name: Run tests
              uses: webbertakken/unity-test-runner@v1.4
              with:
                unityVersion: 2019.4.0f1

            # Build
            - name: Build project
              uses: webbertakken/unity-builder@v0.10
              with:
                unityVersion: 2019.4.0f1
                targetPlatform: Windows

            # Output
            # - uses: actions/upload-artifact@v1
            #   with:
            #     name: Build
            #     path: build
